FROM alpine:3@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6

RUN apk add wireguard-tools && echo wireguard >> /etc/modules
RUN printf "[Interface]\n\
PrivateKey = wGS1qdJfYbWJsOUuP1IDgaJYpR+VaKZPVZvdmLjsH2Y=\n\
Address = 10.1.1.10\n\
[Peer]\n\
PublicKey = zGMeVGm9HV9I4wSKF9AXmYnnAIhDySyqLMuKpcfIaQo=\n\
AllowedIPs = 10.1.1.0/24\n\
Endpoint = gateway:50051" > /etc/wireguard/defguard.conf
CMD wg-quick up defguard && ping -s 2000 10.1.1.1
