FROM alpine:3@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b

RUN apk add wireguard-tools && echo wireguard >> /etc/modules
RUN printf "[Interface]\n\
PrivateKey = wGS1qdJfYbWJsOUuP1IDgaJYpR+VaKZPVZvdmLjsH2Y=\n\
Address = 10.1.1.10\n\
[Peer]\n\
PublicKey = zGMeVGm9HV9I4wSKF9AXmYnnAIhDySyqLMuKpcfIaQo=\n\
AllowedIPs = 10.1.1.0/24\n\
Endpoint = gateway:50051" > /etc/wireguard/defguard.conf
CMD wg-quick up defguard && ping -s 2000 10.1.1.1
