name: E2E tests

on:
  workflow_call:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  test:
    runs-on:
      - codebuild-defguard-core-runner-${{ github.run_id }}-${{ github.run_attempt }}
        instance-size:medium
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4]

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Login to GitHub container registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Export image tag
        run: |
          # strip "refs/heads.” to get just the branch name
          BRANCH=${GITHUB_REF#refs/heads/}
          if [[ "$BRANCH" == release/* ]] || [[ "$BRANCH" == stable/* ]]; then
            # replace '/' with '-' on release branches
            IMAGE_TAG=${BRANCH//\//-}
          else
            # main/dev branch
            IMAGE_TAG=$BRANCH
          fi
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "E2E tests will run on IMAGE_TAG=$IMAGE_TAG"

      - name: Set up Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: "./e2e/.nvmrc"

      - name: Install pnpm
        id: pnpm-install
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
        with:
          # FIXME: temporarily pinned because of https://github.com/pnpm/pnpm/pull/9959
          version: 10.17
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Pull images
        run: docker compose --file './docker-compose.e2e.yaml' pull

      - name: Install E2E dependencies
        working-directory: ./e2e
        run: pnpm install --frozen-lockfile

      - name: Cache Playwright browsers
        id: playwright-cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('e2e/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install playwright chromium
        working-directory: ./e2e
        run: |
          if [[ "${{ steps.playwright-cache.outputs.cache-hit }}" == "true" ]]; then
            # Browsers are cached; only install missing system dependencies.
            npx playwright install-deps chromium
          else
            npx playwright install --with-deps chromium
          fi

      - name: run tests
        working-directory: ./e2e
        run: pnpm test --shard=${{ matrix.shard }}/4

      - name: Stop compose
        if: always()
        run: docker compose --file './docker-compose.e2e.yaml' down

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: failure()
        with:
          name: playwright-report-shard-${{ matrix.shard }}
          path: |
            ./e2e/playwright-report
          retention-days: 7

  trigger-dev-deploy:
    needs: test
    if: ${{ github.event_name != 'pull_request' && github.ref_name == 'dev' }}
    uses: ./.github/workflows/dev-deployment.yml
    secrets: inherit

  trigger-staging-deploy:
    needs: test
    if: ${{ github.event_name != 'pull_request' && startsWith(github.ref_name, 'release/') }}
    uses: ./.github/workflows/staging-deployment.yml
    secrets: inherit
