on:
  push:
    branches:
      - dev
      - 'release/**'
      - 'stable/**'
    paths:
      - "e2e/**"
  pull_request:
    branches:
      - dev
      - 'release/**'
      - 'stable/**'
    paths:
      - "e2e/**"

jobs:
  lint-e2e:
    runs-on:
      - codebuild-defguard-core-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive

      - name: Install NodeJS
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 26

      - name: Install pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          version: 10

      # Change to '--frozen-lockfile' once this gets fixed:
      # https://github.com/pnpm/action-setup/issues/40
      - name: Build and lint e2e
        working-directory: e2e
        run: |
          pnpm install --no-frozen-lockfile
          pnpm lint
