on:
  push:
    branches:
      - dev
      - 'release/**'
      - "stable/**"
    paths:
      - "e2e/**"
  pull_request:
    branches:
      - dev
      - 'release/**'
      - "stable/**"
    paths:
      - "e2e/**"

jobs:
  lint-e2e:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: "./e2e/.nvmrc"
      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
        with:
          # FIXME: temporarily pinned because of https://github.com/pnpm/pnpm/pull/9959
          version: 10.17
          run_install: false
      - name: install deps
        working-directory: ./e2e
        run: pnpm i --frozen-lockfile
      - name: Lint
        working-directory: ./e2e
        run: pnpm lint
