on:
  push:
    branches:
      - dev
      - "release/**"
      - "stable/**"
  pull_request:
    branches:
      - dev
      - "release/**"
      - "stable/**"

permissions:
  contents: read
jobs:
  test-web:
    runs-on:
      - codebuild-defguard-core-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: "recursive"

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 26

      - name: Install pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          version: 11

      - name: install deps
        working-directory: ./web
        run: pnpm i --frozen-lockfile

      - name: Generate paraglide messages
        working-directory: ./web
        run: pnpm exec paraglide-js compile --project ./project.inlang --outdir ./src/paraglide

      - name: Run tests
        working-directory: ./web
        run: pnpm run test
